<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageLinesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $translations = [
            // General
            ['group' => 'general', 'key' => 'welcome', 'text' => ['en' => 'Welcome', 'ar' => 'مرحبا']],
            ['group' => 'general', 'key' => 'hello', 'text' => ['en' => 'Hello', 'ar' => 'السلام عليكم']],
            ['group' => 'general', 'key' => 'goodbye', 'text' => ['en' => 'Goodbye', 'ar' => 'وداعا']],
            ['group' => 'general', 'key' => 'yes', 'text' => ['en' => 'Yes', 'ar' => 'نعم']],
            ['group' => 'general', 'key' => 'no', 'text' => ['en' => 'No', 'ar' => 'لا']],
            ['group' => 'general', 'key' => 'please', 'text' => ['en' => 'Please', 'ar' => 'من فضلك']],
            ['group' => 'general', 'key' => 'thank_you', 'text' => ['en' => 'Thank you', 'ar' => 'شكراً لك']],
            ['group' => 'general', 'key' => 'sorry', 'text' => ['en' => 'Sorry', 'ar' => 'آسف']],
            ['group' => 'general', 'key' => 'congratulations', 'text' => ['en' => 'Congratulations', 'ar' => 'تهانينا']],
            ['group' => 'general', 'key' => 'welcome_back', 'text' => ['en' => 'Welcome back', 'ar' => 'أهلاً بعودتك']],
            ['group' => 'general', 'key' => 'good_morning', 'text' => ['en' => 'Good morning', 'ar' => 'صباح الخير']],
            ['group' => 'general', 'key' => 'good_afternoon', 'text' => ['en' => 'Good afternoon', 'ar' => 'مساء الخير']],
            ['group' => 'general', 'key' => 'good_evening', 'text' => ['en' => 'Good evening', 'ar' => 'مساء الخير']],
            ['group' => 'general', 'key' => 'good_night', 'text' => ['en' => 'Good night', 'ar' => 'تصبح على خير']],
            ['group' => 'general', 'key' => 'take_care', 'text' => ['en' => 'Take care', 'ar' => 'اعتن بنفسك']],
            ['group' => 'general', 'key' => 'see_you_soon', 'text' => ['en' => 'See you soon', 'ar' => 'أراك قريباً']],
            ['group' => 'general', 'key' => 'how_are_you', 'text' => ['en' => 'How are you?', 'ar' => 'كيف حالك؟']],
            ['group' => 'general', 'key' => 'thank_you_for_your_patience', 'text' => ['en' => 'Thank you for your patience', 'ar' => 'شكراً على صبرك']],
            ['group' => 'general', 'key' => 'you_are_welcome', 'text' => ['en' => 'You are welcome', 'ar' => 'على الرحب والسعة']],
            ['group' => 'general', 'key' => 'no_problem', 'text' => ['en' => 'No problem', 'ar' => 'لا مشكلة']],
            ['group' => 'general', 'key' => 'good_luck', 'text' => ['en' => 'Good luck', 'ar' => 'حظاً موفقاً']],
            ['group' => 'general', 'key' => 'take_your_time', 'text' => ['en' => 'Take your time', 'ar' => 'خذ وقتك']],
            ['group' => 'general', 'key' => 'see_you_later', 'text' => ['en' => 'See you later', 'ar' => 'أراك لاحقاً']],
            ['group' => 'general', 'key' => 'dashboard', 'text' => ['en' => 'Dashboard', 'ar' => 'لوحة التحكم']],
            ['group' => 'general', 'key' => 'website_settings', 'text' => ['en' => 'Website Settings', 'ar' => 'اعدادات الموقع']],
            ['group' => 'general', 'key' => 'translations', 'text' => ['en' => 'Translations', 'ar' => 'الترجمات']],
            ['group' => 'general', 'key' => 'role_permissions', 'text' => ['en' => 'Roles & Permissions', 'ar' => 'الأدوار والصلاحيات']],
            ['group' => 'general', 'key' => 'resources', 'text' => ['en' => 'Resources', 'ar' => 'المصادر']],
            ['group' => 'general', 'key' => 'preferences', 'text' => ['en' => 'Preferences', 'ar' => 'التفضيلات']],
            ['group' => 'general', 'key' => 'write_about_yourself', 'text' => ['en' => 'Write about yourself', 'ar' => 'اكتب عن نفسك']],
            ['group' => 'general', 'key' => 'general', 'text' => ['en' => 'General', 'ar' => 'عام']],
            ['group' => 'general', 'key' => 'male', 'text' => ['en' => 'Male', 'ar' => 'ذكر']],
            ['group' => 'general', 'key' => 'female', 'text' => ['en' => 'Female', 'ar' => 'انثي']],
            ['group' => 'general', 'key' => 'profile', 'text' => ['en' => 'Profile', 'ar' => 'الملف الشخصي']],
            ['group' => 'general', 'key' => 'security', 'text' => ['en' => 'Security', 'ar' => 'الحماية']],
            ['group' => 'general', 'key' => 'search', 'text' => ['en' => 'Search', 'ar' => 'إبحث']],
            ['group' => 'general', 'key' => 'page', 'text' => ['en' => 'Page', 'ar' => 'صفحة']],
            ['group' => 'general', 'key' => 'of', 'text' => ['en' => 'of', 'ar' => 'من']],
            ['group' => 'general', 'key' => 'row_per_page', 'text' => ['en' => 'Rows per page', 'ar' => 'الأسطر في الصفحة']],
            ['group' => 'general', 'key' => 'no_results_found', 'text' => ['en' => 'No results found', 'ar' => 'لم يتم العثور على نتائج']],
            ['group' => 'general', 'key' => 'export', 'text' => ['en' => 'Export', 'ar' => 'تصدير']],
            // Auth
            ['group' => 'auth', 'key' => 'login', 'text' => ['en' => 'Login', 'ar' => 'تسجيل الدخول']],
            ['group' => 'auth', 'key' => 'register', 'text' => ['en' => 'Register', 'ar' => 'التسجيل']],
            ['group' => 'auth', 'key' => 'logout', 'text' => ['en' => 'Logout', 'ar' => 'تسجيل الخروج']],
            ['group' => 'auth', 'key' => 'forgot_password', 'text' => ['en' => 'Forgot Password', 'ar' => 'نسيت كلمة المرور']],
            ['group' => 'auth', 'key' => 'reset_password', 'text' => ['en' => 'Reset Password', 'ar' => 'إعادة تعيين كلمة المرور']],
            ['group' => 'auth', 'key' => 'remember_me', 'text' => ['en' => 'Remember Me', 'ar' => 'تذكرني']],
            ['group' => 'auth', 'key' => 'confirm_password', 'text' => ['en' => 'Confirm Password', 'ar' => 'تأكيد كلمة المرور']],
            ['group' => 'auth', 'key' => 'send_reset_link', 'text' => ['en' => 'Send Reset Link', 'ar' => 'إرسال رابط إعادة التعيين']],
            ['group' => 'auth', 'key' => 'verify_email', 'text' => ['en' => 'Verify Your Email Address', 'ar' => 'تحقق من عنوان بريدك الإلكتروني']],
            ['group' => 'auth', 'key' => 'verification_link_sent', 'text' => ['en' => 'A fresh verification link has been sent to your email address.', 'ar' => 'تم إرسال رابط تحقق جديد إلى بريدك الإلكتروني.']],
            ['group' => 'auth', 'key' => 'check_your_email', 'text' => ['en' => 'Check your email for the verification link.', 'ar' => 'تحقق من بريدك الإلكتروني للحصول على رابط التحقق.']],
            ['group' => 'auth', 'key' => 'already_registered', 'text' => ['en' => 'Already registered?', 'ar' => 'مسجل مسبقاً؟']],
            ['group' => 'auth', 'key' => 'confirm', 'text' => ['en' => 'Please confirm your password before continuing.', 'ar' => 'يرجى تأكيد كلمة المرور قبل المتابعة.']],
            ['group' => 'auth', 'key' => 'resend_verification_email', 'text' => ['en' => 'Resend Verification Email', 'ar' => 'إعادة إرسال بريد التحقق']],
            ['group' => 'auth', 'key' => 'login_with', 'text' => ['en' => 'Login with :provider', 'ar' => 'تسجيل الدخول باستخدام :provider']],

            // Navigation
            ['group' => 'nav', 'key' => 'home', 'text' => ['en' => 'Home', 'ar' => 'الرئيسية']],
            ['group' => 'nav', 'key' => 'about', 'text' => ['en' => 'About', 'ar' => 'حول']],
            ['group' => 'nav', 'key' => 'contact', 'text' => ['en' => 'Contact', 'ar' => 'اتصل بنا']],
            ['group' => 'nav', 'key' => 'services', 'text' => ['en' => 'Services', 'ar' => 'الخدمات']],
            ['group' => 'nav', 'key' => 'products', 'text' => ['en' => 'Products', 'ar' => 'المنتجات']],
            ['group' => 'nav', 'key' => 'blog', 'text' => ['en' => 'Blog', 'ar' => 'المدونة']],
            ['group' => 'nav', 'key' => 'home', 'text' => ['en' => 'Home', 'ar' => 'الصفحة الرئيسية']],
            ['group' => 'nav', 'key' => 'portfolio', 'text' => ['en' => 'Portfolio', 'ar' => 'المعرض']],
            ['group' => 'nav', 'key' => 'faq', 'text' => ['en' => 'FAQ', 'ar' => 'الأسئلة الشائعة']],
            ['group' => 'nav', 'key' => 'testimonials', 'text' => ['en' => 'Testimonials', 'ar' => 'الشهادات']],
            ['group' => 'nav', 'key' => 'team', 'text' => ['en' => 'Team', 'ar' => 'الفريق']],
            ['group' => 'nav', 'key' => 'careers', 'text' => ['en' => 'Careers', 'ar' => 'الوظائف']],
            ['group' => 'nav', 'key' => 'privacy_policy', 'text' => ['en' => 'Privacy Policy', 'ar' => 'سياسة الخصوصية']],
            ['group' => 'nav', 'key' => 'terms_of_service', 'text' => ['en' => 'Terms of Service', 'ar' => 'شروط الخدمة']],
            ['group' => 'nav', 'key' => 'sitemap', 'text' => ['en' => 'Sitemap', 'ar' => 'خريطة الموقع']],
            ['group' => 'nav', 'key' => 'support', 'text' => ['en' => 'Support', 'ar' => 'الدعم']],

            // Actions
            ['group' => 'actions', 'key' => 'submit', 'text' => ['en' => 'Submit', 'ar' => 'إرسال']],
            ['group' => 'actions', 'key' => 'cancel', 'text' => ['en' => 'Cancel', 'ar' => 'إلغاء']],
            ['group' => 'actions', 'key' => 'save', 'text' => ['en' => 'Save', 'ar' => 'حفظ']],
            ['group' => 'actions', 'key' => 'edit', 'text' => ['en' => 'Edit', 'ar' => 'تعديل']],
            ['group' => 'actions', 'key' => 'delete', 'text' => ['en' => 'Delete', 'ar' => 'حذف']],
            ['group' => 'actions', 'key' => 'create', 'text' => ['en' => 'Create', 'ar' => 'إنشاء']],
            ['group' => 'actions', 'key' => 'update', 'text' => ['en' => 'Update', 'ar' => 'تحديث']],
            ['group' => 'actions', 'key' => 'search', 'text' => ['en' => 'Search', 'ar' => 'بحث']],
            ['group' => 'actions', 'key' => 'close', 'text' => ['en' => 'Close', 'ar' => 'إغلاق']],
            ['group' => 'actions', 'key' => 'view', 'text' => ['en' => 'View', 'ar' => 'عرض']],
            ['group' => 'actions', 'key' => 'back', 'text' => ['en' => 'Back', 'ar' => 'عودة']],
            ['group' => 'actions', 'key' => 'continue', 'text' => ['en' => 'Continue', 'ar' => 'متابعة']],
            ['group' => 'actions', 'key' => 'confirm', 'text' => ['en' => 'Confirm', 'ar' => 'تأكيد']],
            ['group' => 'actions', 'key' => 'next', 'text' => ['en' => 'Next', 'ar' => 'التالي']],
            ['group' => 'actions', 'key' => 'previous', 'text' => ['en' => 'Previous', 'ar' => 'السابق']],
            ['group' => 'actions', 'key' => 'select', 'text' => ['en' => 'Select', 'ar' => 'اختيار']],
            ['group' => 'actions', 'key' => 'refresh', 'text' => ['en' => 'Refresh', 'ar' => 'تحديث']],
            ['group' => 'actions', 'key' => 'upload', 'text' => ['en' => 'Upload', 'ar' => 'رفع']],
            ['group' => 'actions', 'key' => 'download', 'text' => ['en' => 'Download', 'ar' => 'تحميل']],
            ['group' => 'actions', 'key' => 'drag_and_drop', 'text' => ['en' => 'Drag and drop', 'ar' => 'سحب و الإفلات']],
            ['group' => 'actions', 'key' => 'browse_files', 'text' => ['en' => 'Browse Files', 'ar' => 'تصفح الملفات']],

            // Messages
            ['group' => 'messages', 'key' => 'success', 'text' => ['en' => 'Operation successful', 'ar' => 'تمت العملية بنجاح']],
            ['group' => 'messages', 'key' => 'error', 'text' => ['en' => 'An error occurred', 'ar' => 'حدث خطأ']],
            ['group' => 'messages', 'key' => 'not_found', 'text' => ['en' => 'Not found', 'ar' => 'غير موجود']],
            ['group' => 'messages', 'key' => 'invalid_input', 'text' => ['en' => 'Invalid input', 'ar' => 'مدخلات غير صالحة']],
            ['group' => 'messages', 'key' => 'confirm_delete', 'text' => ['en' => 'Are you sure you want to delete?', 'ar' => 'هل أنت متأكد أنك تريد الحذف؟']],
            ['group' => 'messages', 'key' => 'unauthorized', 'text' => ['en' => 'Unauthorized', 'ar' => 'غير مصرح']],
            ['group' => 'messages', 'key' => 'forbidden', 'text' => ['en' => 'Forbidden', 'ar' => 'ممنوع']],
            ['group' => 'messages', 'key' => 'server_error', 'text' => ['en' => 'Server error', 'ar' => 'خطأ في الخادم']],
            ['group' => 'messages', 'key' => 'validation_failed', 'text' => ['en' => 'Validation failed', 'ar' => 'فشل التحقق']],
            ['group' => 'messages', 'key' => 'timeout', 'text' => ['en' => 'Request timed out', 'ar' => 'انتهت مهلة الطلب']],
            ['group' => 'messages', 'key' => 'loading', 'text' => ['en' => 'Loading...', 'ar' => 'جاري التحميل...']],
            ['group' => 'messages', 'key' => 'no_data', 'text' => ['en' => 'No data available', 'ar' => 'لا توجد بيانات متاحة']],
            ['group' => 'messages', 'key' => 'saved', 'text' => ['en' => 'Data saved successfully', 'ar' => 'تم حفظ البيانات بنجاح']],
            ['group' => 'messages', 'key' => 'deleted', 'text' => ['en' => 'Data deleted successfully', 'ar' => 'تم حذف البيانات بنجاح']],
            ['group' => 'messages', 'key' => 'updated', 'text' => ['en' => 'Data updated successfully', 'ar' => 'تم تحديث البيانات بنجاح']],

            // Attributes
            ['group' => 'attributes', 'key' => 'email', 'text' => ['en' => 'Email', 'ar' => 'البريد الالكتروني']],
            ['group' => 'attributes', 'key' => 'username', 'text' => ['en' => 'Username', 'ar' => 'اسم المستخدم']],
            ['group' => 'attributes', 'key' => 'first_name', 'text' => ['en' => 'First Name', 'ar' => 'الاسم الأول']],
            ['group' => 'attributes', 'key' => 'last_name', 'text' => ['en' => 'Last Name', 'ar' => 'اسم العائلة']],
            ['group' => 'attributes', 'key' => 'bio', 'text' => ['en' => 'Bio', 'ar' => 'الوصف']],
            ['group' => 'attributes', 'key' => 'password', 'text' => ['en' => 'Password', 'ar' => 'كلمة المرور']],
            ['group' => 'attributes', 'key' => 'password_confirmation', 'text' => ['en' => 'Password Confirmation', 'ar' => 'تأكيد كلمة المرور']],
            ['group' => 'attributes', 'key' => 'city', 'text' => ['en' => 'City', 'ar' => 'المدينة']],
            ['group' => 'attributes', 'key' => 'country', 'text' => ['en' => 'Country', 'ar' => 'الدولة']],
            ['group' => 'attributes', 'key' => 'address', 'text' => ['en' => 'Address', 'ar' => 'عنوان السكن']],
            ['group' => 'attributes', 'key' => 'phone', 'text' => ['en' => 'Phone', 'ar' => 'الهاتف']],
            ['group' => 'attributes', 'key' => 'mobile', 'text' => ['en' => 'Mobile', 'ar' => 'الجوال']],
            ['group' => 'attributes', 'key' => 'age', 'text' => ['en' => 'Age', 'ar' => 'العمر']],
            ['group' => 'attributes', 'key' => 'gender', 'text' => ['en' => 'Gender', 'ar' => 'الجنس']],
            ['group' => 'attributes', 'key' => 'day', 'text' => ['en' => 'Day', 'ar' => 'اليوم']],
            ['group' => 'attributes', 'key' => 'month', 'text' => ['en' => 'Month', 'ar' => 'الشهر']],
            ['group' => 'attributes', 'key' => 'year', 'text' => ['en' => 'Year', 'ar' => 'السنة']],
            ['group' => 'attributes', 'key' => 'hour', 'text' => ['en' => 'Hour', 'ar' => 'ساعة']],
            ['group' => 'attributes', 'key' => 'minute', 'text' => ['en' => 'Minute', 'ar' => 'دقيقة']],
            ['group' => 'attributes', 'key' => 'second', 'text' => ['en' => 'Second', 'ar' => 'ثانية']],
            ['group' => 'attributes', 'key' => 'title', 'text' => ['en' => 'Title', 'ar' => 'العنوان']],
            ['group' => 'attributes', 'key' => 'content', 'text' => ['en' => 'Content', 'ar' => 'المُحتوى']],
            ['group' => 'attributes', 'key' => 'description', 'text' => ['en' => 'Description', 'ar' => 'الوصف']],
            ['group' => 'attributes', 'key' => 'excerpt', 'text' => ['en' => 'Excerpt', 'ar' => 'المُلخص']],
            ['group' => 'attributes', 'key' => 'date', 'text' => ['en' => 'Date', 'ar' => 'التاريخ']],
            ['group' => 'attributes', 'key' => 'time', 'text' => ['en' => 'Time', 'ar' => 'الوقت']],
            ['group' => 'attributes', 'key' => 'available', 'text' => ['en' => 'Available', 'ar' => 'مُتاح']],
            ['group' => 'attributes', 'key' => 'size', 'text' => ['en' => 'Size', 'ar' => 'الحجم']],
            ['group' => 'attributes', 'key' => 'video_url', 'text' => ['en' => 'Video URL', 'ar' => 'رابط الفيديو']],
            ['group' => 'attributes', 'key' => 'promo_url', 'text' => ['en' => 'Promo URL', 'ar' => 'رابط الترويج']],
            ['group' => 'attributes', 'key' => 'image', 'text' => ['en' => 'Image', 'ar' => 'الصورة']],
            ['group' => 'attributes', 'key' => 'avatar', 'text' => ['en' => 'Avatar', 'ar' => 'الصورة']],
            ['group' => 'attributes', 'key' => 'initiative', 'text' => ['en' => 'Initiative', 'ar' => 'المبادرة']],
            ['group' => 'attributes', 'key' => 'supervisor', 'text' => ['en' => 'Supervisor', 'ar' => 'المشرف']],
            ['group' => 'attributes', 'key' => 'users', 'text' => ['en' => 'Users', 'ar' => 'المستخدمين']],
            ['group' => 'attributes', 'key' => 'message', 'text' => ['en' => 'Message', 'ar' => 'الرسالة']],
            ['group' => 'attributes', 'key' => 'start_date', 'text' => ['en' => 'Start Date', 'ar' => 'تاريخ البداية']],
            ['group' => 'attributes', 'key' => 'end_date', 'text' => ['en' => 'End Date', 'ar' => 'تاريخ النهاية']],
            ['group' => 'attributes', 'key' => 'user_id', 'text' => ['en' => 'User ID', 'ar' => 'المسوؤل']],
            ['group' => 'attributes', 'key' => 'status_id', 'text' => ['en' => 'Status ID', 'ar' => 'الحالة']],
            ['group' => 'attributes', 'key' => 'prefix', 'text' => ['en' => 'Prefix', 'ar' => 'الرمز']],
            ['group' => 'attributes', 'key' => 'phone_code', 'text' => ['en' => 'Phone Code', 'ar' => 'مقدمة الهاتف']],
            ['group' => 'attributes', 'key' => 'cities_count', 'text' => ['en' => 'Cities Count', 'ar' => 'عدد المدن']],
            ['group' => 'attributes', 'key' => 'add_country', 'text' => ['en' => 'Add Country', 'ar' => 'اضافة دولة']],
            ['group' => 'attributes', 'key' => 'edit_country', 'text' => ['en' => 'Edit Country', 'ar' => 'تعديل الدولة']],
            ['group' => 'attributes', 'key' => 'add_city', 'text' => ['en' => 'Add City', 'ar' => 'اضافة مدينة']],
            ['group' => 'attributes', 'key' => 'edit_city', 'text' => ['en' => 'Edit City', 'ar' => 'تعديل المدينة']],
            ['group' => 'attributes', 'key' => 'education', 'text' => ['en' => 'Education', 'ar' => 'المستوى الدراسي']],
            ['group' => 'attributes', 'key' => 'social_time', 'text' => ['en' => 'Social Time', 'ar' => 'ساعات التواصل الاجتماعي']],
            ['group' => 'attributes', 'key' => 'default_language', 'text' => ['en' => 'Default Language', 'ar' => 'اللغة الافتراضية']],
            ['group' => 'attributes', 'key' => 'platform_title_ar', 'text' => ['en' => 'Platform Title (Arabic)', 'ar' => 'عنوان المنصة بالعربي']],
            ['group' => 'attributes', 'key' => 'platform_title_en', 'text' => ['en' => 'Platform Title (English)', 'ar' => 'عنوان المنصة بالانجليزي']],
            ['group' => 'attributes', 'key' => 'auth_title_ar', 'text' => ['en' => 'Auth Page Text (Arabic)', 'ar' => 'نص صفحة الدخول بالعربي']],
            ['group' => 'attributes', 'key' => 'auth_title_en', 'text' => ['en' => 'Auth Page Text (English)', 'ar' => 'نص صفحة الدخول بالانجليزي']],
            ['group' => 'attributes', 'key' => 'accepted_request_text', 'text' => ['en' => 'Accepted Request Email Text', 'ar' => 'نص البريد الالكتروني لقبول المستخدم']],
            ['group' => 'attributes', 'key' => 'rejected_request_text', 'text' => ['en' => 'Rejected Request Email Text', 'ar' => 'نص البريد الالكتروني لرفض المستخدم']],
            ['group' => 'attributes', 'key' => 'accepted_request_image', 'text' => ['en' => 'Accepted Request Image', 'ar' => 'الصورة']],
            ['group' => 'attributes', 'key' => 'rejected_request_image', 'text' => ['en' => 'Rejected Request Image', 'ar' => 'الصورة']],
            ['group' => 'attributes', 'key' => 'role', 'text' => ['en' => 'Role', 'ar' => 'الدور']],
            ['group' => 'attributes', 'key' => 'display_name', 'text' => ['en' => 'Display Name', 'ar' => 'الاسم']],
            ['group' => 'attributes', 'key' => 'permissions', 'text' => ['en' => 'Permissions', 'ar' => 'الصلاحيات']],
            ['group' => 'attributes', 'key' => 'old_password', 'text' => ['en' => 'Old Password', 'ar' => 'كلمة المرور']],
            ['group' => 'attributes', 'key' => 'name_ar', 'text' => ['en' => 'Name (Arabic)', 'ar' => 'الاسم بالعربي']],
            ['group' => 'attributes', 'key' => 'name_en', 'text' => ['en' => 'Name (English)', 'ar' => 'الاسم بالانجليزي']],
            ['group' => 'attributes', 'key' => 'roles', 'text' => ['en' => 'Roles', 'ar' => 'الدور']],
            ['group' => 'attributes', 'key' => 'country', 'text' => ['en' => 'Country', 'ar' => 'البلد']],
            ['group' => 'attributes', 'key' => 'comment', 'text' => ['en' => 'Comment', 'ar' => 'التعليق']],
            ['group' => 'attributes', 'key' => 'nationality', 'text' => ['en' => 'Nationality', 'ar' => 'الجنسية']],
            ['group' => 'attributes', 'key' => 'interrupt_rules.*.description', 'text' => ['en' => 'Description', 'ar' => 'الوصف']],
            ['group' => 'attributes', 'key' => 'birthday', 'text' => ['en' => 'Birthday', 'ar' => 'تاريخ الميلاد']],
            ['group' => 'attributes', 'key' => 'birthday_milady', 'text' => ['en' => 'Milady Birthday', 'ar' => 'تاريخ الميلاد']],
            ['group' => 'attributes', 'key' => 'birthday_type', 'text' => ['en' => 'Birthday Type', 'ar' => 'نوع تاريخ الميلاد']],
            ['group' => 'attributes', 'key' => 'country_code', 'text' => ['en' => 'Country Code', 'ar' => 'رمز الدولة']],

            // Errors
            ['group' => 'errors', 'key' => 'not_found', 'text' => ['en' => 'Page not found', 'ar' => 'الصفحة غير موجودة']],
            ['group' => 'errors', 'key' => 'forbiden', 'text' => ['en' => 'Forbidden', 'ar' => 'ممنوع']],
            ['group' => 'errors', 'key' => 'server_error', 'text' => ['en' => 'Server error', 'ar' => 'خطأ في الخادم']],

            // User
            ['group' => 'user', 'key' => 'ge,eral', 'text' => ['en' => 'ge,eral', 'ar' => 'الملف الشخصي']],
            ['group' => 'user', 'key' => 'settings', 'text' => ['en' => 'Settings', 'ar' => 'الإعدادات']],
            ['group' => 'user', 'key' => 'account', 'text' => ['en' => 'Account', 'ar' => 'الحساب']],
            ['group' => 'user', 'key' => 'update_ge,eral', 'text' => ['en' => 'Update ge,eral', 'ar' => 'تحديث الملف الشخصي']],
            ['group' => 'user', 'key' => 'update_avatar', 'text' => ['en' => 'Update Avatar', 'ar' => 'تحديث الصورة']],
            ['group' => 'user', 'key' => 'change_password', 'text' => ['en' => 'Change Password', 'ar' => 'تغيير كلمة المرور']],
            ['group' => 'user', 'key' => 'logout', 'text' => ['en' => 'Logout', 'ar' => 'تسجيل الخروج']],
            ['group' => 'user', 'key' => 'notifications', 'text' => ['en' => 'Notifications', 'ar' => 'الإشعارات']],
            ['group' => 'user', 'key' => 'privacy', 'text' => ['en' => 'Privacy', 'ar' => 'الخصوصية']],
            ['group' => 'user', 'key' => 'language', 'text' => ['en' => 'Language', 'ar' => 'اللغة']],
            ['group' => 'user', 'key' => 'delete_account', 'text' => ['en' => 'Delete Account', 'ar' => 'حذف الحساب']],

            // Social
            ['group' => 'social', 'key' => 'share', 'text' => ['en' => 'Share', 'ar' => 'مشاركة']],
            ['group' => 'social', 'key' => 'like', 'text' => ['en' => 'Like', 'ar' => 'إعجاب']],
            ['group' => 'social', 'key' => 'comment', 'text' => ['en' => 'Comment', 'ar' => 'تعليق']],
            ['group' => 'social', 'key' => 'follow', 'text' => ['en' => 'Follow', 'ar' => 'متابعة']],
            ['group' => 'social', 'key' => 'unfollow', 'text' => ['en' => 'Unfollow', 'ar' => 'إلغاء متابعة']],
            ['group' => 'social', 'key' => 'message', 'text' => ['en' => 'Message', 'ar' => 'رسالة']],
            ['group' => 'social', 'key' => 'post', 'text' => ['en' => 'Post', 'ar' => 'نشر']],
            ['group' => 'social', 'key' => 'reply', 'text' => ['en' => 'Reply', 'ar' => 'رد']],
            ['group' => 'social', 'key' => 'tag', 'text' => ['en' => 'Tag', 'ar' => 'وسم']],
            ['group' => 'social', 'key' => 'report', 'text' => ['en' => 'Report', 'ar' => 'تقرير']],

            // Misc
            ['group' => 'misc', 'key' => 'more', 'text' => ['en' => 'More', 'ar' => 'المزيد']],
            ['group' => 'misc', 'key' => 'less', 'text' => ['en' => 'Less', 'ar' => 'أقل']],
            ['group' => 'misc', 'key' => 'back', 'text' => ['en' => 'Back', 'ar' => 'رجوع']],
            ['group' => 'misc', 'key' => 'next', 'text' => ['en' => 'Next', 'ar' => 'التالي']],
            ['group' => 'misc', 'key' => 'previous', 'text' => ['en' => 'Previous', 'ar' => 'السابق']],
            ['group' => 'misc', 'key' => 'loading', 'text' => ['en' => 'Loading...', 'ar' => 'جارٍ التحميل...']],
            ['group' => 'misc', 'key' => 'no_data', 'text' => ['en' => 'No data available', 'ar' => 'لا توجد بيانات']],
            ['group' => 'misc', 'key' => 'search_placeholder', 'text' => ['en' => 'Search...', 'ar' => 'ابحث...']],
            ['group' => 'misc', 'key' => 'filter', 'text' => ['en' => 'Filter', 'ar' => 'تصفية']],
            ['group' => 'misc', 'key' => 'clear', 'text' => ['en' => 'Clear', 'ar' => 'مسح']],
        ];

        foreach ($translations as $translation) {
            DB::table('language_lines')->insert([
                'group' => $translation['group'],
                'key' => $translation['key'],
                'text' => json_encode($translation['text']),
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
